"""
Tasks router - /api/tasks (formerly /api/task-records)
"""
from __future__ import annotations

from pathlib import Path
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from backend.db.database import get_db
from backend.db import crud
from backend.db.models_extra import TaskRecord
from backend.api.schemas import TaskRecordOut, TaskRecordsResponse
from backend.config import OUTPUTS_TASK_CLUSTER


router = APIRouter()


def _load_task_records_from_csv() -> list[TaskRecordOut]:
    """
    Load task records from the CSV files generated by the pipeline.
    This is called when the DB is empty or when refreshing from pipeline output.
    """
    # Use the existing function from offline_task_dashboard
    # We need to add project root to path for this import to work
    import sys
    project_root = str(Path(__file__).resolve().parent.parent.parent)
    if project_root not in sys.path:
        sys.path.insert(0, project_root)

    from offline_task_dashboard import load_task_records

    clusters_path = OUTPUTS_TASK_CLUSTER / "clusters.csv"
    mapping_path = OUTPUTS_TASK_CLUSTER / "cluster_load_mapping.csv"

    try:
        records = load_task_records(clusters_path=clusters_path, mapping_path=mapping_path)
    except FileNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Pipeline output not found: {e}",
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to load task records: {e}",
        )

    return [
        TaskRecordOut(
            session=r.session,
            task_id=r.task_id,
            cluster=r.cluster,
            level=r.level,
            label=r.label,
        )
        for r in records
    ]


@router.get("", response_model=TaskRecordsResponse)
def get_task_records(
    session: Annotated[str | None, Query(description="Filter by session name")] = None,
    skip: Annotated[int, Query(ge=0)] = 0,
    limit: Annotated[int, Query(ge=1, le=500)] = 100,
    db: Session = Depends(get_db),
):
    """
    Get task records. If DB is empty, falls back to reading from CSV pipeline output.
    """
    count = crud.get_task_records_count(db)

    if count == 0:
        # DB empty - load from CSV
        csv_records = _load_task_records_from_csv()
        if not csv_records:
            return TaskRecordsResponse(records=[])

        # Persist to DB for future queries
        crud.upsert_task_records(
            db=db,
            records=[r.model_dump() for r in csv_records],
        )

        # Return filtered
        if session:
            return TaskRecordsResponse(records=[r for r in csv_records if r.session == session])
        return TaskRecordsResponse(records=csv_records)

    # DB has data - query from DB
    db_records = crud.get_task_records(db, session=session, skip=skip, limit=limit)
    return TaskRecordsResponse(
        records=[
            TaskRecordOut(
                session=r.session,
                task_id=r.task_id,
                cluster=r.cluster,
                level=r.level,
                label=r.label,
            )
            for r in db_records
        ]
    )
